-- Upgrade System - New Ability Card Structure Property Tests
-- Property-based tests for new ability card generation
-- Feature: ability-selection

require("tests.spec_helper")

local upgrade_system = require("src.systems.upgrade_system")
local ability_registry = require("src.models.ability_registry")
local Hero = require("src.entities.hero")
local ArcaneBolt = require("src.entities.abilities.arcane_bolt")
local lqc = require("lqc.quickcheck")
local property = require("lqc.property")
local lqc_gen = require("lqc.lqc_gen")

describe("Upgrade System - New Ability Card Structure Property Tests", function()
  before_each(function()
    -- Initialize lua-quickcheck with 100 iterations
    lqc.init(100, 100)  -- 100 tests, 100 shrinks
  end)

  -- Feature: ability-selection, Property 5: New Ability Card Structure
  describe("Property 5: New Ability Card Structure", function()
    it("should include all required fields (id, type, abilityId, name, description, iconType, apply) for any new ability card", function()
      -- **Validates: Requirements 2.4, 2.5, 5.1, 5.2, 5.3, 5.4**

      -- Property: For any new ability card generated by the upgrade system,
      -- the card must include all required fields: id, type ("new_ability"),
      -- abilityId, name, description, iconType, and a valid apply function.

      property "All new ability cards have required structure" {
        generators = {
          lqc_gen.choose(1, 100)  -- Iteration counter
        },
        check = function(iteration)
          -- Create hero with varying number of abilities (0-4 to ensure slots available)
          local abilityCount = math.random(0, 4)
          local hero = Hero:new(360, 1180)
          
          -- Add random number of abilities to hero
          for i = 1, abilityCount do
            local ability = ArcaneBolt:new()
            ability.id = "test_ability_" .. i  -- Give unique IDs
            hero:addAbility(ability)
          end
          
          -- Initialize upgrade system
          local upgradeCallback = function() end
          upgrade_system.initialize(hero, upgradeCallback)
          
          -- Get available upgrades
          local available = upgrade_system.getAvailableUpgrades()
          
          -- Find all new_ability type cards
          local newAbilityCards = {}
          for _, upgrade in ipairs(available) do
            if upgrade.type == "new_ability" then
              table.insert(newAbilityCards, upgrade)
            end
          end
          
          -- If no new ability cards found, this might be valid if no unlocked abilities
          -- or hero already has all available abilities
          if #newAbilityCards == 0 then
            -- Check if there are any unlocked abilities in the registry
            local hasUnlockedAbilities = false
            for abilityId, _ in pairs(ability_registry.abilities) do
              if ability_registry.isUnlocked(abilityId) then
                hasUnlockedAbilities = true
                break
              end
            end
            
            -- If there are unlocked abilities and hero has < 5 abilities,
            -- we should have new ability cards
            if hasUnlockedAbilities and #hero.abilities < 5 then
              return false, "Should have new ability cards when unlocked abilities exist and hero has < 5 abilities"
            end
            
            -- Otherwise, it's valid to have no new ability cards
            return true
          end
          
          -- Verify each new ability card has all required fields
          for _, card in ipairs(newAbilityCards) do
            -- Verify 'id' field exists and is a string
            if card.id == nil then
              return false, "New ability card missing 'id' field"
            end
            
            if type(card.id) ~= "string" then
              return false, "New ability card 'id' field is not a string: " .. type(card.id)
            end
            
            -- Verify 'id' follows format "new_ability_<abilityId>"
            if not string.match(card.id, "^new_ability_") then
              return false, "New ability card 'id' does not follow format 'new_ability_<abilityId>': " .. card.id
            end
            
            -- Verify 'type' field exists and equals "new_ability"
            if card.type == nil then
              return false, "New ability card missing 'type' field"
            end
            
            if card.type ~= "new_ability" then
              return false, "New ability card 'type' field is not 'new_ability': " .. tostring(card.type)
            end
            
            -- Verify 'abilityId' field exists and is a string
            if card.abilityId == nil then
              return false, "New ability card missing 'abilityId' field"
            end
            
            if type(card.abilityId) ~= "string" then
              return false, "New ability card 'abilityId' field is not a string: " .. type(card.abilityId)
            end
            
            -- Verify 'name' field exists and is a string
            if card.name == nil then
              return false, "New ability card missing 'name' field"
            end
            
            if type(card.name) ~= "string" then
              return false, "New ability card 'name' field is not a string: " .. type(card.name)
            end
            
            -- Verify 'name' is not empty
            if card.name == "" then
              return false, "New ability card 'name' field is empty"
            end
            
            -- Verify 'description' field exists and is a string
            if card.description == nil then
              return false, "New ability card missing 'description' field"
            end
            
            if type(card.description) ~= "string" then
              return false, "New ability card 'description' field is not a string: " .. type(card.description)
            end
            
            -- Verify 'iconType' field exists and is a string
            if card.iconType == nil then
              return false, "New ability card missing 'iconType' field"
            end
            
            if type(card.iconType) ~= "string" then
              return false, "New ability card 'iconType' field is not a string: " .. type(card.iconType)
            end
            
            -- Verify 'apply' field exists and is a function
            if card.apply == nil then
              return false, "New ability card missing 'apply' field"
            end
            
            if type(card.apply) ~= "function" then
              return false, "New ability card 'apply' field is not a function: " .. type(card.apply)
            end
          end
          
          -- Cleanup
          upgrade_system.cleanup()
          
          return true
        end
      }
    end)

    it("should have id field matching format 'new_ability_<abilityId>' for any new ability card", function()
      -- **Validates: Requirements 2.4, 5.1**

      -- Property: For any new ability card, the id field should match the format
      -- "new_ability_<abilityId>" where abilityId is the referenced ability

      property "New ability card id matches format" {
        generators = {
          lqc_gen.choose(1, 100)  -- Iteration counter
        },
        check = function(iteration)
          -- Create hero with varying number of abilities (0-4)
          local abilityCount = math.random(0, 4)
          local hero = Hero:new(360, 1180)
          
          for i = 1, abilityCount do
            local ability = ArcaneBolt:new()
            ability.id = "test_ability_" .. i
            hero:addAbility(ability)
          end
          
          -- Initialize upgrade system
          upgrade_system.initialize(hero, function() end)
          
          -- Get available upgrades
          local available = upgrade_system.getAvailableUpgrades()
          
          -- Check all new_ability cards
          for _, card in ipairs(available) do
            if card.type == "new_ability" then
              -- Verify id format
              local expectedId = "new_ability_" .. card.abilityId
              if card.id ~= expectedId then
                upgrade_system.cleanup()
                return false, "Card id '" .. card.id .. "' does not match expected format 'new_ability_" .. card.abilityId .. "'"
              end
            end
          end
          
          upgrade_system.cleanup()
          return true
        end
      }
    end)

    it("should have a valid apply function that can be called for any new ability card", function()
      -- **Validates: Requirements 2.5, 5.4**

      -- Property: For any new ability card, the apply function should be callable
      -- and should handle the hero parameter correctly

      property "New ability card apply function is valid and callable" {
        generators = {
          lqc_gen.choose(1, 100)  -- Iteration counter
        },
        check = function(iteration)
          -- Create hero with varying number of abilities (0-4)
          local abilityCount = math.random(0, 4)
          local hero = Hero:new(360, 1180)
          
          for i = 1, abilityCount do
            local ability = ArcaneBolt:new()
            ability.id = "test_ability_" .. i
            hero:addAbility(ability)
          end
          
          -- Initialize upgrade system
          upgrade_system.initialize(hero, function() end)
          
          -- Get available upgrades
          local available = upgrade_system.getAvailableUpgrades()
          
          -- Find a new_ability card
          local newAbilityCard = nil
          for _, card in ipairs(available) do
            if card.type == "new_ability" then
              newAbilityCard = card
              break
            end
          end
          
          -- If no new ability card found, skip this iteration
          if not newAbilityCard then
            upgrade_system.cleanup()
            return true
          end
          
          -- Verify apply function is callable
          local initialCount = #hero.abilities
          
          -- Try to call the apply function
          local success, result = pcall(newAbilityCard.apply, hero)
          
          if not success then
            upgrade_system.cleanup()
            return false, "Apply function threw error: " .. tostring(result)
          end
          
          -- Verify result is a boolean
          if type(result) ~= "boolean" then
            upgrade_system.cleanup()
            return false, "Apply function should return boolean, got: " .. type(result)
          end
          
          -- If apply succeeded, verify ability was added
          if result == true then
            if #hero.abilities ~= initialCount + 1 then
              upgrade_system.cleanup()
              return false, "Apply function returned true but ability count did not increase"
            end
          end
          
          upgrade_system.cleanup()
          return true
        end
      }
    end)

    it("should reference only unlocked abilities in the abilityId field for any new ability card", function()
      -- **Validates: Requirements 2.2, 5.1**

      -- Property: For any new ability card, the abilityId field should reference
      -- an ability that is unlocked in the ability registry

      property "New ability cards reference only unlocked abilities" {
        generators = {
          lqc_gen.choose(1, 100)  -- Iteration counter
        },
        check = function(iteration)
          -- Create hero with varying number of abilities (0-4)
          local abilityCount = math.random(0, 4)
          local hero = Hero:new(360, 1180)
          
          for i = 1, abilityCount do
            local ability = ArcaneBolt:new()
            ability.id = "test_ability_" .. i
            hero:addAbility(ability)
          end
          
          -- Initialize upgrade system
          upgrade_system.initialize(hero, function() end)
          
          -- Get available upgrades
          local available = upgrade_system.getAvailableUpgrades()
          
          -- Check all new_ability cards
          for _, card in ipairs(available) do
            if card.type == "new_ability" then
              -- Verify the abilityId references an unlocked ability
              if not ability_registry.isUnlocked(card.abilityId) then
                upgrade_system.cleanup()
                return false, "New ability card references locked ability: " .. card.abilityId
              end
            end
          end
          
          upgrade_system.cleanup()
          return true
        end
      }
    end)

    it("should not reference abilities the hero already has for any new ability card", function()
      -- **Validates: Requirements 2.1, 5.1**

      -- Property: For any new ability card, the abilityId should not match
      -- any ability the hero already has equipped

      property "New ability cards do not reference hero's existing abilities" {
        generators = {
          lqc_gen.choose(1, 100)  -- Iteration counter
        },
        check = function(iteration)
          -- Create hero with varying number of abilities (0-4)
          local abilityCount = math.random(0, 4)
          local hero = Hero:new(360, 1180)
          
          -- Build set of hero's ability IDs
          local heroAbilityIds = {}
          for i = 1, abilityCount do
            local ability = ArcaneBolt:new()
            ability.id = "test_ability_" .. i
            hero:addAbility(ability)
            heroAbilityIds[ability.id] = true
          end
          
          -- Initialize upgrade system
          upgrade_system.initialize(hero, function() end)
          
          -- Get available upgrades
          local available = upgrade_system.getAvailableUpgrades()
          
          -- Check all new_ability cards
          for _, card in ipairs(available) do
            if card.type == "new_ability" then
              -- Verify the abilityId is not in hero's current abilities
              if heroAbilityIds[card.abilityId] then
                upgrade_system.cleanup()
                return false, "New ability card references ability hero already has: " .. card.abilityId
              end
            end
          end
          
          upgrade_system.cleanup()
          return true
        end
      }
    end)

    it("should have consistent field types across all new ability cards", function()
      -- **Validates: Requirements 2.4, 2.5, 5.1, 5.2, 5.3, 5.4**

      -- Property: All new ability cards should have consistent field types
      -- (id: string, type: string, abilityId: string, name: string,
      -- description: string, iconType: string, apply: function)

      property "All new ability cards have consistent field types" {
        generators = {
          lqc_gen.choose(1, 100)  -- Iteration counter
        },
        check = function(iteration)
          -- Create hero with varying number of abilities (0-4)
          local abilityCount = math.random(0, 4)
          local hero = Hero:new(360, 1180)
          
          for i = 1, abilityCount do
            local ability = ArcaneBolt:new()
            ability.id = "test_ability_" .. i
            hero:addAbility(ability)
          end
          
          -- Initialize upgrade system
          upgrade_system.initialize(hero, function() end)
          
          -- Get available upgrades
          local available = upgrade_system.getAvailableUpgrades()
          
          -- Expected field types
          local expectedTypes = {
            id = "string",
            type = "string",
            abilityId = "string",
            name = "string",
            description = "string",
            iconType = "string",
            apply = "function"
          }
          
          -- Check all new_ability cards
          for _, card in ipairs(available) do
            if card.type == "new_ability" then
              -- Verify each field has the correct type
              for fieldName, expectedType in pairs(expectedTypes) do
                local actualType = type(card[fieldName])
                if actualType ~= expectedType then
                  upgrade_system.cleanup()
                  return false, "Field '" .. fieldName .. "' has wrong type: expected " .. expectedType .. ", got " .. actualType
                end
              end
            end
          end
          
          upgrade_system.cleanup()
          return true
        end
      }
    end)
  end)
end)
