-- Upgrade System - Unlocked Abilities Only Property Tests
-- Property-based tests for ensuring only unlocked abilities are offered
-- Feature: ability-selection

require("tests.spec_helper")

local upgrade_system = require("src.systems.upgrade_system")
local ability_registry = require("src.models.ability_registry")
local Hero = require("src.entities.hero")
local ArcaneBolt = require("src.entities.abilities.arcane_bolt")
local lqc = require("lqc.quickcheck")
local property = require("lqc.property")
local lqc_gen = require("lqc.lqc_gen")

describe("Upgrade System - Unlocked Abilities Only Property Tests", function()
  before_each(function()
    -- Initialize lua-quickcheck with 100 iterations
    lqc.init(100, 100)  -- 100 tests, 100 shrinks
  end)

  -- Feature: ability-selection, Property 7: Unlocked Abilities Only
  describe("Property 7: Unlocked Abilities Only", function()
    it("should only reference unlocked abilities in new_ability cards generated by generateCards", function()
      -- **Validates: Requirements 2.2, 7.2, 7.4**

      -- Property: For any new_ability card generated by the upgrade system,
      -- the referenced abilityId must correspond to an ability that returns
      -- true from isUnlocked(abilityId).

      property "All new_ability cards reference only unlocked abilities" {
        generators = {
          lqc_gen.choose(0, 4)  -- Generate hero with 0-4 abilities
        },
        check = function(abilityCount)
          -- Create hero with specified number of abilities
          local hero = Hero:new(360, 1180)

          -- Add random number of abilities to hero (0-4)
          for i = 1, abilityCount do
            local ability = ArcaneBolt:new()
            ability.id = "test_ability_" .. i  -- Give unique IDs
            hero:addAbility(ability)
          end

          -- Initialize upgrade system
          local upgradeCallback = function() end
          upgrade_system.initialize(hero, upgradeCallback)

          -- Generate upgrade cards
          local cards = upgrade_system.generateCards(3)

          -- Check all new_ability cards
          for _, card in ipairs(cards) do
            if card.type == "new_ability" then
              -- Verify the card has an abilityId field
              if not card.abilityId then
                upgrade_system.cleanup()
                return false, "New ability card missing abilityId field"
              end

              -- Verify the abilityId references an unlocked ability
              local isUnlocked = ability_registry.isUnlocked(card.abilityId)

              if not isUnlocked then
                upgrade_system.cleanup()
                return false, "New ability card references locked ability: " .. tostring(card.abilityId)
              end

              -- Verify isUnlocked returns a boolean
              if type(isUnlocked) ~= "boolean" then
                upgrade_system.cleanup()
                return false, "isUnlocked returned non-boolean type: " .. type(isUnlocked)
              end
            end
          end

          -- Cleanup
          upgrade_system.cleanup()

          return true
        end
      }
    end)

    it("should only reference unlocked abilities in new_ability cards from getAvailableUpgrades", function()
      -- **Validates: Requirements 2.2, 7.2, 7.4**

      -- Property: For any new_ability card in the available upgrades pool,
      -- the referenced abilityId must correspond to an ability that returns
      -- true from isUnlocked(abilityId).

      property "All new_ability cards in available upgrades reference only unlocked abilities" {
        generators = {
          lqc_gen.choose(0, 4)  -- Generate hero with 0-4 abilities
        },
        check = function(abilityCount)
          -- Create hero with specified number of abilities
          local hero = Hero:new(360, 1180)

          -- Add random number of abilities to hero (0-4)
          for i = 1, abilityCount do
            local ability = ArcaneBolt:new()
            ability.id = "test_ability_" .. i  -- Give unique IDs
            hero:addAbility(ability)
          end

          -- Initialize upgrade system
          local upgradeCallback = function() end
          upgrade_system.initialize(hero, upgradeCallback)

          -- Get available upgrades
          local available = upgrade_system.getAvailableUpgrades()

          -- Check all new_ability cards
          for _, upgrade in ipairs(available) do
            if upgrade.type == "new_ability" then
              -- Verify the upgrade has an abilityId field
              if not upgrade.abilityId then
                upgrade_system.cleanup()
                return false, "New ability upgrade missing abilityId field"
              end

              -- Verify the abilityId references an unlocked ability
              local isUnlocked = ability_registry.isUnlocked(upgrade.abilityId)

              if not isUnlocked then
                upgrade_system.cleanup()
                return false, "New ability upgrade references locked ability: " .. tostring(upgrade.abilityId)
              end

              -- Verify isUnlocked returns a boolean
              if type(isUnlocked) ~= "boolean" then
                upgrade_system.cleanup()
                return false, "isUnlocked returned non-boolean type: " .. type(isUnlocked)
              end
            end
          end

          -- Cleanup
          upgrade_system.cleanup()

          return true
        end
      }
    end)

    it("should verify that all new_ability cards reference abilities that exist in the registry", function()
      -- **Validates: Requirements 2.2, 7.2, 7.4**

      -- Property: For any new_ability card, the abilityId must reference
      -- an ability that exists in the ability registry (getAbility returns non-nil).

      property "All new_ability cards reference existing abilities in registry" {
        generators = {
          lqc_gen.choose(0, 4)  -- Generate hero with 0-4 abilities
        },
        check = function(abilityCount)
          -- Create hero with specified number of abilities
          local hero = Hero:new(360, 1180)

          -- Add random number of abilities to hero (0-4)
          for i = 1, abilityCount do
            local ability = ArcaneBolt:new()
            ability.id = "test_ability_" .. i  -- Give unique IDs
            hero:addAbility(ability)
          end

          -- Initialize upgrade system
          local upgradeCallback = function() end
          upgrade_system.initialize(hero, upgradeCallback)

          -- Generate upgrade cards
          local cards = upgrade_system.generateCards(3)

          -- Check all new_ability cards
          for _, card in ipairs(cards) do
            if card.type == "new_ability" then
              -- Verify the card has an abilityId field
              if not card.abilityId then
                upgrade_system.cleanup()
                return false, "New ability card missing abilityId field"
              end

              -- Verify the abilityId exists in the registry
              local abilityDef = ability_registry.getAbility(card.abilityId)

              if not abilityDef then
                upgrade_system.cleanup()
                return false, "New ability card references non-existent ability: " .. tostring(card.abilityId)
              end

              -- Verify the ability definition has the unlocked field
              if abilityDef.unlocked == nil then
                upgrade_system.cleanup()
                return false, "Ability definition for '" .. tostring(card.abilityId) .. "' missing unlocked field"
              end

              -- Verify the unlocked field is true (since this is a new_ability card)
              if abilityDef.unlocked ~= true then
                upgrade_system.cleanup()
                return false, "New ability card references locked ability (unlocked=" .. tostring(abilityDef.unlocked) .. "): " .. tostring(card.abilityId)
              end
            end
          end

          -- Cleanup
          upgrade_system.cleanup()

          return true
        end
      }
    end)

    it("should maintain consistency between isUnlocked and ability definition's unlocked field", function()
      -- **Validates: Requirements 2.2, 7.2, 7.4**

      -- Property: For any new_ability card, the result of isUnlocked(abilityId)
      -- should match the unlocked field in the ability definition.

      property "isUnlocked result matches ability definition's unlocked field" {
        generators = {
          lqc_gen.choose(0, 4)  -- Generate hero with 0-4 abilities
        },
        check = function(abilityCount)
          -- Create hero with specified number of abilities
          local hero = Hero:new(360, 1180)

          -- Add random number of abilities to hero (0-4)
          for i = 1, abilityCount do
            local ability = ArcaneBolt:new()
            ability.id = "test_ability_" .. i  -- Give unique IDs
            hero:addAbility(ability)
          end

          -- Initialize upgrade system
          local upgradeCallback = function() end
          upgrade_system.initialize(hero, upgradeCallback)

          -- Get available upgrades
          local available = upgrade_system.getAvailableUpgrades()

          -- Check all new_ability cards
          for _, upgrade in ipairs(available) do
            if upgrade.type == "new_ability" then
              -- Get the unlock status via isUnlocked
              local isUnlocked = ability_registry.isUnlocked(upgrade.abilityId)

              -- Get the ability definition
              local abilityDef = ability_registry.getAbility(upgrade.abilityId)

              -- Verify definition exists
              if not abilityDef then
                upgrade_system.cleanup()
                return false, "Ability definition not found for: " .. tostring(upgrade.abilityId)
              end

              -- Verify isUnlocked matches the definition's unlocked field
              local expectedUnlocked = (abilityDef.unlocked == true)

              if isUnlocked ~= expectedUnlocked then
                upgrade_system.cleanup()
                return false, "isUnlocked(" .. tostring(upgrade.abilityId) .. ") returned " .. tostring(isUnlocked) .. " but definition.unlocked is " .. tostring(abilityDef.unlocked)
              end

              -- Since this is a new_ability card, both should be true
              if not isUnlocked then
                upgrade_system.cleanup()
                return false, "New ability card references ability with isUnlocked=false: " .. tostring(upgrade.abilityId)
              end
            end
          end

          -- Cleanup
          upgrade_system.cleanup()

          return true
        end
      }
    end)

    it("should never generate new_ability cards for locked abilities across multiple iterations", function()
      -- **Validates: Requirements 2.2, 7.2, 7.4**

      -- Property: Across multiple card generation cycles, no new_ability card
      -- should ever reference a locked ability.

      property "No new_ability cards for locked abilities across iterations" {
        generators = {
          lqc_gen.choose(1, 100)  -- Iteration counter
        },
        check = function(iteration)
          -- Create hero with varying number of abilities (0-4)
          local abilityCount = math.random(0, 4)
          local hero = Hero:new(360, 1180)

          -- Add random number of abilities to hero
          for i = 1, abilityCount do
            local ability = ArcaneBolt:new()
            ability.id = "test_ability_" .. i  -- Give unique IDs
            hero:addAbility(ability)
          end

          -- Initialize upgrade system
          local upgradeCallback = function() end
          upgrade_system.initialize(hero, upgradeCallback)

          -- Generate multiple sets of cards to test consistency
          local iterations = math.random(1, 5)
          for j = 1, iterations do
            local cards = upgrade_system.generateCards(3)

            -- Check all new_ability cards
            for _, card in ipairs(cards) do
              if card.type == "new_ability" then
                -- Verify the abilityId references an unlocked ability
                if not ability_registry.isUnlocked(card.abilityId) then
                  upgrade_system.cleanup()
                  return false, "New ability card references locked ability in iteration " .. j .. ": " .. tostring(card.abilityId)
                end
              end
            end
          end

          -- Cleanup
          upgrade_system.cleanup()

          return true
        end
      }
    end)

    it("should only offer abilities that can be successfully instantiated via createInstance", function()
      -- **Validates: Requirements 2.2, 7.2, 7.4**

      -- Property: For any new_ability card, calling createInstance(abilityId)
      -- should return a valid instance (not nil).

      property "All new_ability cards reference instantiable abilities" {
        generators = {
          lqc_gen.choose(0, 4)  -- Generate hero with 0-4 abilities
        },
        check = function(abilityCount)
          -- Create hero with specified number of abilities
          local hero = Hero:new(360, 1180)

          -- Add random number of abilities to hero (0-4)
          for i = 1, abilityCount do
            local ability = ArcaneBolt:new()
            ability.id = "test_ability_" .. i  -- Give unique IDs
            hero:addAbility(ability)
          end

          -- Initialize upgrade system
          local upgradeCallback = function() end
          upgrade_system.initialize(hero, upgradeCallback)

          -- Get available upgrades
          local available = upgrade_system.getAvailableUpgrades()

          -- Check all new_ability cards
          for _, upgrade in ipairs(available) do
            if upgrade.type == "new_ability" then
              -- Try to create an instance of the ability
              local instance = ability_registry.createInstance(upgrade.abilityId)

              -- Verify instance was created successfully
              if not instance then
                upgrade_system.cleanup()
                return false, "createInstance returned nil for ability referenced in new_ability card: " .. tostring(upgrade.abilityId)
              end

              -- Verify instance is a table (object)
              if type(instance) ~= "table" then
                upgrade_system.cleanup()
                return false, "createInstance returned non-table type for: " .. tostring(upgrade.abilityId)
              end

              -- Verify instance has expected ability properties
              if not instance.id then
                upgrade_system.cleanup()
                return false, "Created instance missing id field for: " .. tostring(upgrade.abilityId)
              end
            end
          end

          -- Cleanup
          upgrade_system.cleanup()

          return true
        end
      }
    end)
  end)
end)
