require("tests.spec_helper")
local mathUtils = require("src.utils.math")

describe("Math Utilities", function()
    describe("clamp", function()
        it("should constrain a value within a range", function()
            assert.is.equal(10, mathUtils.clamp(15, 0, 10))
            assert.is.equal(0, mathUtils.clamp(-5, 0, 10))
            assert.is.equal(5, mathUtils.clamp(5, 0, 10))
        end)
    end)

    describe("lerp", function()
        it("should linearly interpolate between two values", function()
            assert.is.equal(5, mathUtils.lerp(0, 10, 0.5))
            assert.is.equal(0, mathUtils.lerp(0, 10, 0))
            assert.is.equal(10, mathUtils.lerp(0, 10, 1))
        end)
    end)

    describe("isValid", function()
        it("should detect valid and invalid numbers", function()
            assert.is_true(mathUtils.isValid(42))
            assert.is_true(mathUtils.isValid(0))
            assert.is_false(mathUtils.isValid(0/0)) -- NaN
            assert.is_false(mathUtils.isValid(math.huge))
        end)
    end)

    describe("sign", function()
        it("should return the correct sign of a number", function()
            assert.is.equal(1, mathUtils.sign(10))
            assert.is.equal(-1, mathUtils.sign(-5))
            assert.is.equal(0, mathUtils.sign(0))
        end)
    end)

    describe("round", function()
        it("should round to the nearest integer", function()
            assert.is.equal(3, mathUtils.round(2.6))
            assert.is.equal(2, mathUtils.round(2.4))
            assert.is.equal(3, mathUtils.round(2.5))
        end)
    end)
end)
