require("tests.spec_helper")
local stringUtils = require("src.utils.string")

describe("String Utilities", function()
    describe("split", function()
        it("should split a string by a delimiter", function()
            local result = stringUtils.split("apple,banana,cherry", ",")
            assert.is.equal(3, #result)
            assert.is.equal("apple", result[1])
            assert.is.equal("banana", result[2])
            assert.is.equal("cherry", result[3])
        end)

        it("should return the whole string if delimiter is not found", function()
            local result = stringUtils.split("apple", ",")
            assert.is.equal(1, #result)
            assert.is.equal("apple", result[1])
        end)
    end)

    describe("trim", function()
        it("should remove leading and trailing whitespace", function()
            assert.is.equal("hello", stringUtils.trim("  hello  "))
            assert.is.equal("hello world", stringUtils.trim("\t\n hello world \r"))
        end)
    end)

    describe("capitalize", function()
        it("should capitalize the first letter of a string", function()
            assert.is.equal("Hello", stringUtils.capitalize("hello"))
            assert.is.equal("World", stringUtils.capitalize("World"))
            assert.is.equal("", stringUtils.capitalize(""))
        end)
    end)
end)
